### PR TITLE
Upgrade ruby to 2.2.2

### PR DESCRIPTION
**Pull request by luvtechno**
#### WHY

We love the latest.

### CODE REVIEW

**Comment by creasty** [comment]
> We love the latest.

<3

**Comment by luvtechno** [comment]
@creasty can you merge?

**Comment by creasty** [comment]
@luvtechno not sure... it just “looks” good to me, tho

**Comment by luvtechno** [comment]
Cheers

**Comment by creasty** [comment]
hooray!

**Pull request merged**
